Repository janbjorge/pgqueuer, pull requests merged in 2025-08, with the labels that each got.

#453 Allow callable factory fn
  pgqueuer/factories.py
  pgqueuer/supervisor.py
  test/test_factories.py
  test/test_superviser.py
Labels: enhancement

#460 docs: add callable factory example
  docs/index.rst
  examples/callable_factory/README.md
  examples/callable_factory/consumer.py
  examples/callable_factory/producer.py
Labels: codex

#462 docs: document SyncPsycopgDriver and driver selection
  README.md
  docs/driver.md
Labels: codex

#463 Updated readme
  README.md
Labels: documentation
